spring.application.name=arena
server.port=8079

spring.datasource.url=jdbc:mysql://MySQL-8.2:3306/event_arena?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path= /api

jwt.secret=a07364bf38e968fc1de7183543cd3ffa0de9864991653b6ad82e105195647859
jwt.expiration=86400000
