server:
  port: 8084
spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://mysql-xzxz.alwaysdata.net:3306/xzxz_kavalenok?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:xzxz}
    password: ${DB_PASSWORD:nTuxTgCCDMw97x!}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false