spring.application.name=demo
server.port = 8087

spring.datasource.url=jdbc:mysql://MySQL-8.2:3306/bogdanovich_database?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.servlet.context-path= /api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=d6bc96083f34b2c3df6cff7e7804de2b1701720fcfe5e2d0cef8eafa439e08cb
jwt.expiration=86400000
